# Generated by Django 5.0.4 on 2024-05-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0002_alter_score_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
            ],
        ),
    ]
